# Generated by Django 4.2 on 2023-08-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangpt_aituber_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='닉네임'),
        ),
    ]
