# Generated by Django 4.2 on 2023-09-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yangpt_aituber_app', '0002_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.TextField(blank=True, null=True, verbose_name='유저 채팅')),
                ('response', models.TextField(blank=True, null=True, verbose_name='AI 답변')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='Fine_tuning_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_prompts', models.IntegerField(verbose_name='프롬프트 갯수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='파인 튜닝 실행일')),
            ],
            options={
                'db_table': 'fine_tuning_logs',
            },
        ),
    ]
