# Generated by Django 4.2 on 2023-09-06 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yangpt_aituber_app', '0003_chat_fine_tuning_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='response',
        ),
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True, verbose_name='AI 답변')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yangpt_aituber_app.chat')),
            ],
            options={
                'db_table': 'ai_response',
            },
        ),
    ]
