# Generated by Django 4.2 on 2023-09-23 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yangpt_aituber_app', '0004_remove_chat_response_airesponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airesponse',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_response', to='yangpt_aituber_app.chat'),
        ),
    ]
